import { mkdtemp, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

import { describe, expect, it } from "vitest";

import { StorageService } from "./storage.service.js";

describe("StorageService", () => {
  it("rejects storage keys that were not generated by the server", async () => {
    const storage = createStorageService();

    await expect(storage.delete("../statement.pdf")).rejects.toThrow(
      "Invalid storage key.",
    );
  });

  it("writes private files under generated UUID keys", async () => {
    const storageRoot = await mkdtemp(join(tmpdir(), "secure-room-storage-"));
    setStorageEnv(storageRoot);
    const storage = new StorageService();

    const storageKey = await storage.savePrivateFile(
      Buffer.from("body"),
      "XLSX",
    );

    expect(storageKey).toMatch(/^[0-9a-f-]{36}\.xlsx$/);

    await storage.delete(storageKey);
    await rm(storageRoot, { recursive: true, force: true });
  });
});

function createStorageService(): StorageService {
  setStorageEnv(join(tmpdir(), "secure-room-storage"));
  return new StorageService();
}

function setStorageEnv(storageDir: string): void {
  process.env.DATABASE_URL =
    "postgresql://postgres:postgres@localhost:5432/secure_room?schema=public";
  process.env.JWT_SECRET = "development-secret-for-tests";
  process.env.CLIENT_ORIGIN = "http://localhost:5173";
  process.env.STORAGE_DIR = storageDir;
}
